### ISSUE TITLE
add angular-server to Hedley

### ISSUE THREAD

**Issue by mirzu** [fourkitchens/train-headless#13]
Headley - https://github.com/Gizra/generator-hedley
AngularJS Server - https://github.com/saymedia/angularjs-server

**Comment by mattgrill** [comment]
I've checked out AngularJS-Server. From what I can see, it looks alright. Some issues below which might prevent us from using it in our training. 

* Using version of `express` that is a major-version out of date.
* The demo does not work. 
* Need to learn `AngularJS` to use this. 
  * While not totally insurmountable, probably not likely given the time frame. 
  * Kevin may be able to help, since he already has experience with `Angular`.

I'd like to suggest that we offer this at a later date, and perhaps use it on a project before we commit to teaching it. 

To hopefully move this forward. I've been working on our headless-drupal-nodejs template. I'd like to wrap this up into a `yeoman` generator. At that point we'd have two generators working, `hedley` and this nodejs/express one. 

Thoughts welcome.

**Comment by mattgrill** [comment]
![](http://media.giphy.com/media/wOqylfb8Ammsg/giphy.gif)
